name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      plugin_name:
        description: Plugin target to build
        required: true
      plugin_version:
        description: Version label for this manual build
        required: true
  push:
    tags:
    - "*@*"

env:
  BUILD_TYPE: Release
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DISPLAY: :0
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  SCCACHE_GHA_ENABLED: true
  SCCACHE_CACHE_MULTIARCH: 1

jobs:
  parse-tag:
    runs-on: ubuntu-latest
    outputs:
      plugin_name: ${{ steps.parse.outputs.plugin_name }}
      plugin_version: ${{ steps.parse.outputs.plugin_version }}
      plugin_folder: ${{ steps.parse.outputs.plugin_folder }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: Parse tag
      id: parse
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          TAG="${{ inputs.plugin_name }}@${{ inputs.plugin_version }}"
        else
          TAG="${{ github.ref_name }}"
        fi
        NAME=$(python script/action_name.py "$TAG" name)
        VERSION=$(python script/action_name.py "$TAG" version)
        FOLDER=$(python script/action_name.py "$TAG" folder)
        echo "plugin_name=$NAME" >> "$GITHUB_OUTPUT"
        echo "plugin_version=$VERSION" >> "$GITHUB_OUTPUT"
        echo "plugin_folder=$FOLDER" >> "$GITHUB_OUTPUT"
        echo "Parsed: name=$NAME  version=$VERSION  folder=$FOLDER"

  build:
    name: build-${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    needs: [ parse-tag ]
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Windows
          os: windows-2022
          artifact_name: plugin-win
        - name: macOS
          os: macos-26
          macos_arch: "x86_64;arm64"
          artifact_name: plugin-macos
        - name: Linux
          os: ubuntu-22.04
          artifact_name: plugin-linux

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Install Clang (Windows)
      if: runner.os == 'Windows'
      uses: egor-tensin/setup-clang@v2
      with:
        version: latest
        platform: x86
        cc: 1

    - name: Install IPP (Windows)
      if: runner.os == 'Windows'
      run: |
        nuget install intelipp.static.win-x64 -Version 2022.3.0.387

    - name: Install Dependencies (macOS)
      if: runner.os == 'macOS'
      run: brew install cmake ninja

    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt-get install libx11-dev libfreetype-dev libfontconfig1-dev libasound2-dev libxrandr-dev libxinerama-dev libxcursor-dev

    - name: Install JUCE's Linux Deps
      if: runner.os == 'Linux'
      run: |
        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list

        sudo apt-get update && sudo apt install libasound2-dev libx11-dev libxinerama-dev libxext-dev libfreetype6-dev libwebkit2gtk-4.1-dev libglu1-mesa-dev xvfb ninja-build intel-oneapi-ipp-devel
        sudo /usr/bin/Xvfb $DISPLAY &

    - name: Generate Build Files (Windows)
      if: runner.os == 'Windows'
      run: |
        cmake -G "Ninja" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang -DCMAKE_BUILD_TYPE=Release -DBUILD_STANDALONE=OFF -DCPP_SIMD_DETECTOR_BUILD_EXAMPLES=OFF -DQWQDSP_BUILD_TESTS=OFF -DIPP_SHARED=OFF -DBUILD_IN_CI=1 -DCI_PLUGIN_TARGET=${{ needs.parse-tag.outputs.plugin_folder }} -S . -B ./build

    - name: Generate Build Files (macOS)
      if: runner.os == 'macOS'
      run: |
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DBUILD_STANDALONE=OFF -DCMAKE_OSX_ARCHITECTURES="${{ matrix.macos_arch }}" -DCPP_SIMD_DETECTOR_BUILD_EXAMPLES=OFF -DQWQDSP_BUILD_TESTS=OFF -DIPP_SHARED=OFF -DBUILD_IN_CI=1 -DCI_PLUGIN_TARGET=${{ needs.parse-tag.outputs.plugin_folder }} -S . -B ./build

    - name: Generate Build Files (Linux)
      if: runner.os == 'Linux'
      run: |
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DBUILD_STANDALONE=OFF -DCPP_SIMD_DETECTOR_BUILD_EXAMPLES=OFF -DQWQDSP_BUILD_TESTS=OFF -DIPP_SHARED=OFF -DBUILD_IN_CI=1 -DCI_PLUGIN_TARGET=${{ needs.parse-tag.outputs.plugin_folder }} -S . -B ./build

    - name: Build Plugin
      run: |
        cmake --build ./build --target ${{ needs.parse-tag.outputs.plugin_name }}_All --config Release

    - name: Upload (Windows)
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          ./build/plugins/${{ needs.parse-tag.outputs.plugin_folder }}/*_artefacts/Release/VST3
          !./build/plugins/${{ needs.parse-tag.outputs.plugin_folder }}/*_artefacts/Release/VST3/*.exp
          !./build/plugins/${{ needs.parse-tag.outputs.plugin_folder }}/*_artefacts/Release/VST3/*.lib

    - name: Upload (macOS)
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          ./build/plugins/${{ needs.parse-tag.outputs.plugin_folder }}/*_artefacts/Release/AU
          ./build/plugins/${{ needs.parse-tag.outputs.plugin_folder }}/*_artefacts/Release/VST3
          !./build/plugins/${{ needs.parse-tag.outputs.plugin_folder }}/*_artefacts/Release/VST3/*.exp
          !./build/plugins/${{ needs.parse-tag.outputs.plugin_folder }}/*_artefacts/Release/VST3/*.lib

    - name: Upload (Linux)
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          ./build/plugins/${{ needs.parse-tag.outputs.plugin_folder }}/*_artefacts/Release/LV2
          ./build/plugins/${{ needs.parse-tag.outputs.plugin_folder }}/*_artefacts/Release/VST3
          !./build/plugins/${{ needs.parse-tag.outputs.plugin_folder }}/*_artefacts/Release/VST3/*.exp
          !./build/plugins/${{ needs.parse-tag.outputs.plugin_folder }}/*_artefacts/Release/VST3/*.lib

  release:
    runs-on: ubuntu-latest
    needs: [ parse-tag, build ]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v8
      with:
        name: plugin-win
        path: artifacts/plugin-win

    - name: Download macOS artifact
      uses: actions/download-artifact@v8
      with:
        name: plugin-macos
        path: artifacts/plugin-macos

    - name: Download Linux artifact
      uses: actions/download-artifact@v8
      with:
        name: plugin-linux
        path: artifacts/plugin-linux

    - name: Append tag to artifacts
      run: |
        set -euo pipefail

        TAG_NAME=${GITHUB_REF#refs/tags/}
        REPO_NAME="${{ github.event.repository.name }}"

        MAC_RELEASE_DIR=$(find "$GITHUB_WORKSPACE/artifacts/plugin-macos" -type d -name "Release" | head -n 1)
        WIN_RELEASE_DIR=$(find "$GITHUB_WORKSPACE/artifacts/plugin-win" -type d -name "Release" | head -n 1)
        LINUX_RELEASE_DIR=$(find "$GITHUB_WORKSPACE/artifacts/plugin-linux" -type d -name "Release" | head -n 1)

        test -n "$WIN_RELEASE_DIR" || { echo "ERROR: Windows Release dir not found"; exit 1; }
        test -n "$MAC_RELEASE_DIR" || { echo "ERROR: macOS Release dir not found"; exit 1; }
        test -n "$LINUX_RELEASE_DIR" || { echo "ERROR: Linux Release dir not found"; exit 1; }

        DEST_DIR="$GITHUB_WORKSPACE/artifacts"

        cd "$WIN_RELEASE_DIR"
        zip -r "${REPO_NAME}-win-${TAG_NAME}.zip" .
        cp "${REPO_NAME}-win-${TAG_NAME}.zip" "$DEST_DIR/"

        cd "$MAC_RELEASE_DIR"
        zip -r "${REPO_NAME}-macos-${TAG_NAME}.zip" .
        cp "${REPO_NAME}-macos-${TAG_NAME}.zip" "$DEST_DIR/"

        cd "$LINUX_RELEASE_DIR"
        zip -r "${REPO_NAME}-linux-${TAG_NAME}.zip" .
        cp "${REPO_NAME}-linux-${TAG_NAME}.zip" "$DEST_DIR/"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        tag_name: ${{ github.ref_name }}
        name: ${{ needs.parse-tag.outputs.plugin_name }} ${{ needs.parse-tag.outputs.plugin_version }}
        body: Release ${{ needs.parse-tag.outputs.plugin_name }} ${{ needs.parse-tag.outputs.plugin_version }}
        files: |
          artifacts/*-win-*.zip
          artifacts/*-macos-*.zip
          artifacts/*-linux-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
